# ReadTheDocs configuration for PandaDock
version: 2

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py

# Python requirements
python:
  install:
    - requirements: docs/requirements.txt