name: Publish Python Package
on:
  release:
    types: [created]
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build and publish to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      run: |
        python -m build
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*

  # Uncomment when ready to publish to the main PyPI
  # deploy-prod:
  #   runs-on: ubuntu-latest
  #   needs: deploy-test  # Optional: Ensures TestPyPI works before publishing to PyPI
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: '3.10'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install build twine
  #   - name: Build and publish to PyPI
  #     env:
  #       TWINE_USERNAME: __token__
  #       TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
  #     run: |
  #       python -m build
  #       twine upload dist/*
